### Listar todos os jogadores
GET http://localhost:3000/jogadores
Content-Type: application/json

### Cadastrar novo jogador
POST http://localhost:3000/jogadores
Content-Type: application/json

{
  "nome": "Emannuel",
  "nickname": "manuzera"
}

### Testar jogador com nickname duplicado
POST http://localhost:3000/jogadores
Content-Type: application/json

{
  "nome": "Gedean",
  "nickname": "gdzz"
}